# Project Language
language: java
# Don't use sudo
sudo: false
# Set Branch that trigger CI Pipeline
branches:
  only:
    - master
# JDK Version
jdk:
  - openjdk8
# Skip default Install Phase
install: true
# Cache /.m2 to speed up builds
cache: 
  directories:
    - $HOME/.m2
# Build Script
script:
  - mvn clean package
# Post proccess after success build
after_success:
  - bash <(curl -s https://codecov.io/bash)
# Deploy to Heroku
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_TOKEN
  app: hexagonal-architecture
  on:
    repo: cjcalmeida/hexagonal-architecture
