spring:
  data:
    jpa:
      repositories:
        enabled: false
    jdbc:
      repositories:
        enabled: false
  thymeleaf:
    enabled: false
  jpa:
    open-in-view: false
---
# Inbound Adapters
spring:
    profiles: api
---
spring:
  profiles: web
  thymeleaf:
    cache: true
    enabled: true
---
spring:
  profiles: ws
---
#Outbound Adapters
spring:
  profiles: inmemory
---
spring:
  profiles: jdbc
  datasource:
    password: 1234 # Login password of the database.
    username: sa # Login username of the database.
    schema: classpath:schema.sql
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
  data:
    jdbc:
      repositories:
        enabled: true
  h2:
    console:
      path: /h2
      enabled: true
---
spring:
  profiles: jpa
  datasource:
    password: 1234 # Login password of the database.
    username: sa # Login username of the database.
    schema: classpath:schema.sql
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    show-sql: true
  h2:
    console:
      path: /h2
      enabled: true
---
spring:
  profiles: heroku
  profiles.include: api,ws,web,jpa
server:
  port: ${PORT}